### ISSUE TITLE
How to compile it?

### ISSUE THREAD

**Issue by hahaopsmeow** [romracer/Xposed#2]
Hi romracer!

I want to learn some xposed stuff. Could you please explain:
- which toolchain do I need? 
- how to compile it?

Thank you in advance!

**Comment by hahaopsmeow** [comment]
Sorry, found [myself](https://github.com/rovo89/Xposed/issues/9)

**Comment by romracer** [comment]
You can also take a look at https://github.com/romracer/XposedTools
