### ISSUE TITLE
Does systemless works?

### ISSUE THREAD

**Issue by hahaopsmeow** [romracer/Xposed#3]
Hi romracer,

I see you have some systemless commits. I just want to know where it works and how to pack systemless Xposed for installation?

If it works I want to continue by cloning your repo.

Thank you for your effort!

**Comment by romracer** [comment]
Hi,

Systemless definitely works.  It requires a phone using the standard Android boot image format (same as systemless SuperSU).  If you are going to build it, you will need this repo and my XposedTools repo.  You will need @rovo89's android_art repo.  The XposedTools repo has a readme written by @rovo89 that explains how to use it.  See romracer/XposedTools@af1c1aea for details on how to use systemless specifically.  You will also need a patched XposedInstaller.  I have a repo for that, or you can find a download in my post on XDA.

**Comment by hahaopsmeow** [comment]
Hi @romracer ,

Thank you very much for your reply! I just read all docs and I will use your sources of XposedTools because you already have systemless support in your source tree! (Great job! Thank you a lot!).

p.s. I am just beginning with Xposed. I didn't make a single build yet.
